DROP DATABASE IF EXISTS bdfenix;
CREATE DATABASE bdfenix;

USE bdfenix;

CREATE TABLE VENDEDOR(
  ID_VEND     INT          NOT NULL PRIMARY KEY AUTO_INCREMENT,
  DNI_VEND    CHAR(8)      NOT NULL UNIQUE,
  NOM_VEND    VARCHAR(50)  NOT NULL,
  APE_VEND    VARCHAR(50)  NOT NULL,
  DIREC_VEND  VARCHAR(80)  NOT NULL,
  TELEF_VEND  VARCHAR(15)  NOT NULL UNIQUE
);

CREATE TABLE USUARIO(
  USERNAME  VARCHAR(15)  NOT NULL PRIMARY KEY,
  CLAVE     VARCHAR(50)  NOT NULL,
  ID_VEND   INT          NOT NULL,
  FOREIGN KEY (ID_VEND) REFERENCES VENDEDOR(ID_VEND)
);

CREATE TABLE CLIENTE(
  ID_CLI     INT          NOT NULL PRIMARY KEY AUTO_INCREMENT,
  DNI_CLI    CHAR(8)      NOT NULL UNIQUE,
  NOM_CLI    VARCHAR(50)  NOT NULL,
  APE_CLI    VARCHAR(50)  NOT NULL,
  DIREC_CLI  VARCHAR(80)  NOT NULL,
  TELEF_CLI  VARCHAR(15)  NOT NULL UNIQUE
);
